# Generated by Django 4.0.5 on 2023-08-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_seller_company_name_seller_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
